# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import connection_pb2 as connection__pb2


class ConnectionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Conn = channel.stream_stream(
        '/es.Connection/Conn',
        request_serializer=connection__pb2.ConnRequest.SerializeToString,
        response_deserializer=connection__pb2.ConnResponse.FromString,
        )


class ConnectionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Conn(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ConnectionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Conn': grpc.stream_stream_rpc_method_handler(
          servicer.Conn,
          request_deserializer=connection__pb2.ConnRequest.FromString,
          response_serializer=connection__pb2.ConnResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'es.Connection', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
