# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='connection.proto',
  package='es',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x63onnection.proto\x12\x02\x65s\"\x1e\n\x0b\x43onnRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\" \n\x0c\x43onnResponse\x12\x10\n\x08response\x18\x01 \x01(\t2=\n\nConnection\x12/\n\x04\x43onn\x12\x0f.es.ConnRequest\x1a\x10.es.ConnResponse\"\x00(\x01\x30\x01\x62\x06proto3')
)




_CONNREQUEST = _descriptor.Descriptor(
  name='ConnRequest',
  full_name='es.ConnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='es.ConnRequest.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=54,
)


_CONNRESPONSE = _descriptor.Descriptor(
  name='ConnResponse',
  full_name='es.ConnResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='es.ConnResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['ConnRequest'] = _CONNREQUEST
DESCRIPTOR.message_types_by_name['ConnResponse'] = _CONNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnRequest = _reflection.GeneratedProtocolMessageType('ConnRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONNREQUEST,
  __module__ = 'connection_pb2'
  # @@protoc_insertion_point(class_scope:es.ConnRequest)
  ))
_sym_db.RegisterMessage(ConnRequest)

ConnResponse = _reflection.GeneratedProtocolMessageType('ConnResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONNRESPONSE,
  __module__ = 'connection_pb2'
  # @@protoc_insertion_point(class_scope:es.ConnResponse)
  ))
_sym_db.RegisterMessage(ConnResponse)



_CONNECTION = _descriptor.ServiceDescriptor(
  name='Connection',
  full_name='es.Connection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=90,
  serialized_end=151,
  methods=[
  _descriptor.MethodDescriptor(
    name='Conn',
    full_name='es.Connection.Conn',
    index=0,
    containing_service=None,
    input_type=_CONNREQUEST,
    output_type=_CONNRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONNECTION)

DESCRIPTOR.services_by_name['Connection'] = _CONNECTION

# @@protoc_insertion_point(module_scope)
